### ISSUE TITLE
Nette 2.4 compatibility

### ISSUE THREAD

**Issue by misaon** [ublaboo/simple-http-auth#1]
Can you make support for Nette 2.4?
Thanks ;)

**Comment by paveljanda** [comment]
I can make support for Nette 2.4. Not for Nette 2.4RC<xxxx>. Please tell me when there is a stable Nette 2.4.

**Comment by JanGalek** [comment]
I sent PR,  simple http auth already support 2.4 ;), tested 2.4RC

**Comment by paveljanda** [comment]
Thanks.
